### ISSUE TITLE
Support jupyterlab >= 2.0.0

### ISSUE THREAD

**Issue by itaistopel** [parente/jupyterlab-quickopen#11]
Hi.

Currently quickopen doesn't support jupyterlab 2.0.0 or above.
Is there an option to support those versions?

Thanks a million.
bye.

**Comment by parente** [comment]
I haven't had time to update the extension to support JupyterLab 2.x yet. I'm happy to review a pull request if you manage to get it working before I do.

**Comment by itaistopel** [comment]
@parente Could you please give me permissions to push to a new branch in order to open a PR?

**Comment by parente** [comment]
@itaistopel Thanks for offering to contribute!

The typical GitHub flow for contributing to projects you don't own is to create a fork of the repository and submit a pull request to the upstream from your fork. Here's a couple short guides about how to do it if you're new to that workflow:

* https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork
* https://reflectoring.io/github-fork-and-pull/

**Comment by itaistopel** [comment]
@parente 
installation works now, https://github.com/itaistopel/jupyterlab-quickopen/tree/feature/jupyterlab_2_x_support
but it looks like something is wrong and the search itself doesn't work.
Could you please take a look?
Thanks!

**Comment by parente** [comment]
@itaistopel It'll be easier to debug and review the code in the pull request UI. You can continue to push commits even after you open the pull request. Would you mind opening one and we can continue the conversation there? Thanks!

**Comment by parente** [comment]
I've pushed 0.5.0 to pypi and npm. Thanks again for the effort!
